baseURL: "https://hugocodex.org"
languageCode: "en-us"
title: "Hugo Codex"

params:
  description: "Hugo, the website framework that is super fast, because fast is simply better."

disableKinds: 
  - taxonomy
  - taxonomyTerm
  - term
  - RSS

markup:
  goldmark:
    renderer:
      unsafe: true