baseURL: "https://hugocodex.org"
defaultContentLanguage: en
languageCode: "en-us"

disableKinds: 
  - taxonomy
  - taxonomyTerm
  - term

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: English
    title: Hugo Codex
    params:
      description: "Hugo, the website framework that is super fast, because fast is simply better."
    contentDir: content/en
    weight: 1
    permalinks: 
      posts: blog/:filename
  es:
    languageName: Spaans
    title: Hugo Codex
    params:
      description: "Hugo, que es súper rápido, porque rápido es simplemente mejor."
    contentDir: content/es
    weight: 2
    permalinks:
      posts: blog/:filename
      getting-started: empezando/:filename
